jdbcSettings:
  url: "jdbc:mysql://mysql.cc.puv.fi:3306/e1800945_northwind"
  username: "e1800945"
  password: "jFm7Wb8FejHE"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "fi.vamk.e1800945.northwind1"